<script src="{{ url('assets/admin/js/jquery-3.7.1.min.js') }}"></script>
<script src="{{ url('assets/admin/js/moment.min.js') }}"></script>
<script src="{{ url('assets/admin/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url('assets/admin/js/bootstrap-datetimepicker.min.js') }}"></script>
<script src="{{ url('assets/admin/js/feather.min.js') }}"></script>
<script src="{{ url('assets/admin/js/jquery.slimscroll.min.js') }}"></script>
<script src="{{ url('assets/admin/js/script.js') }}"></script>
<script src="{{ url('assets/admin/js/select2.min.js')}}"></script>
<script src="{{ url('assets/admin/js/filepond.js')}}"></script>
<script src="{{ url('assets/admin/js/apexcharts.min.js')}}"></script>
<script src="{{ url('assets/admin/js/chart-data.js')}}"></script>
